services:
  alpineA:
    image: alpine
    healthcheck:
      test: ping -c 5 172.29.0.1 > /dev/null 2>&1 || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      perimeter:
        #condition: service_healthy
        condition: service_started
    cap_add:
      - NET_ADMIN
    post_start:
      - command: ip route add default via 172.29.0.1
    entrypoint: tail -f /dev/null
    networks:
      client:
        ipv4_address: 172.29.0.2
  
  dvwa:
    image: vulnerables/web-dvwa
    healthcheck:
      test: ping -c 5 172.28.0.1 > /dev/null 2>&1 || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    cap_add:
      - NET_ADMIN
    post_start:
      - command: ip route add default via 172.28.0.1
    depends_on:
      perimeter:
        condition: service_started
        #condition: service_healthy
    networks:
      dmz:
        ipv4_address: 172.28.0.2


  perimeter:
    build: framework/openwrt
    hostname: perimeter
    restart: unless-stopped
    volumes:
      - ./config/router/perimeter/init.sh:/etc/uci-defaults/init.sh
      #- ./config/router/perimeter/ospfd.conf:/etc/quagga/ospfd.conf
    healthcheck:
      test: test -e /.started && (ping -c 4 8.8.8.8 > /dev/null 2>&1 || exit 1)
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    privileged: true
    networks:
      internet:
        ipv4_address: 172.30.0.2
      client:
        ipv4_address: 172.29.0.1
      dmz:
        ipv4_address: 172.28.0.1

networks:
  internet:
    name: internet
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

  client:
    name: client
    driver: macvlan
    internal: true
    ipam:
      config:
        - subnet: 172.29.0.0/24
  
  dmz:
    name: dmz
    driver: macvlan
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/24
