services:
  dind:
    image: docker:28.2-dind
    restart: unless-stopped
    ports: # Remember to use 127.0.0.1, NOT localhost
      - 5000:5000 # dvwa
      - 6000:6000 # scada db
      - 8080:8080 # LuCI perimeter
      - 8081:8081 # LuCI enterprise
      - 8082:8082 # LuCI industrial
    volumes:
      - ./DVI_dind:/DVI
    privileged: true