services:
  dind:
    image: docker:28.2-dind
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 5000:5000
    volumes:
      - ./DVI_dind:/DVI
    privileged: true