services:
  plugin:
    restart: always
    build:
      context: ./
    #image: gabibbo97/lidite-dovesnap:latest
    volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/var/run/openvswitch:/var/run/openvswitch
      - /opt/faucetconfrpc:/faucetconfrpc
    network_mode: host
    pid: host
    extra_hosts:
      - 'faucetconfrpc:${FAUCETCONFRPC_IP}'
    depends_on:
      ovs:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_CHROOT
    security_opt: ['apparmor:unconfined']
    command:
      - --debug
      - --faucetconfrpc_addr=faucetconfrpc
      - --faucetconfrpc_port=59999
      - --faucetconfrpc_keydir=/faucetconfrpc
    labels:
      - "dovesnap.namespace=primary"
  ovs:
    restart: always
    image: iqtlabs/openvswitch:v2.16.0
    healthcheck:
      test: 'ovs-vsctl show'
    volumes:
      - /usr/local/var/run/openvswitch:/usr/local/var/run/openvswitch
      - ovs-data:/etc/openvswitch
    network_mode: host
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    labels:
      - "dovesnap.namespace=primary"

  faucet:
    restart: always
    image: 'c65sdn/faucet:1.0.16'
    networks:
      - dovesnap
    volumes:
      - /var/log/faucet:/var/log/faucet
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - '6653:6653'
    environment:
      FAUCET_CONFIG_STAT_RELOAD: '1'
      FAUCET_CONFIG_AUTO_REVERT: '1'
    labels:
      - "dovesnap.namespace=standalone"

  gauge:
    restart: always
    image: 'c65sdn/gauge:1.0.16'
    networks:
      - dovesnap
    volumes:
      - /var/log/gauge:/var/log/gauge
      - ../configs/dovesnap/gauge.yaml:/etc/faucet/gauge.yaml
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - '6654:6653'
    environment:
      GAUGE_CONFIG: '/etc/faucet/gauge.yaml'
      GAUGE_CONFIG_STAT_RELOAD: '1'
      GAUGE_CONFIG_AUTO_REVERT: '1'
    labels:
      - "dovesnap.namespace=standalone"

  faucet_certstrap:
    restart: on-failure
    image: 'iqtlabs/faucet-certstrap:v0.22.26'
    network_mode: none
    volumes:
      - /opt/faucetconfrpc:/opt/faucetconfrpc
    command:
      - /opt/faucetconfrpc
      - faucetconfrpc
    labels:
      - "dovesnap.namespace=standalone"
      
  faucetconfrpc:
    restart: always
    image: 'iqtlabs/faucetconfrpc:v0.22.26'
    environment:
      PYTHONUNBUFFERED: '1'
    networks:
      - dovesnap
    volumes:
      - /opt/faucetconfrpc:/faucetconfrpc
      - '${FAUCET_PREFIX}/etc/faucet:/etc/faucet'
    ports:
      - 59999:59999
    command:
      - --key=/faucetconfrpc/faucetconfrpc.key
      - --cert=/faucetconfrpc/faucetconfrpc.crt
      - --cacert=/faucetconfrpc/faucetconfrpc-ca.crt
      - --host=faucetconfrpc
      - --config_dir=/etc/faucet
    depends_on:
      - faucet
      - gauge
    labels:
      - "dovesnap.namespace=standalone"

networks:
  dovesnap:

volumes:
  ovs-data:
